#Gradle
org.gradle.jvmargs=-Xmx2048M -Dfile.encoding=UTF-8

# Build Cache
org.gradle.caching=true

# Parallel execution
org.gradle.parallel=true

# Configuration cache (Gradle 8+ feature)
org.gradle.configuration-cache=true

#Kotlin
kotlin.code.style=official

#Android
android.useAndroidX=true
android.nonTransitiveRClass=true

#MPP
kotlin.mpp.enableCInteropCommonization=true

kotlin.native.binary.sourceInfoType=libbacktrace

#compiler translate Unit-returning suspend functions to async Swift with the Void return type
kotlin.native.binary.unitSuspendFunctionObjCExport=proper

#Dokka
org.jetbrains.dokka.experimental.gradle.pluginMode=V2Enabled
org.jetbrains.dokka.experimental.gradle.pluginMode.noWarn=true
