[versions]
## library version
libraryVersion = "0.1.2"

## SDK Versions
minSdk = "26"
compileSdk = "36"

# Dependencies
android-gradle-plugin = "8.13.0"

kotlin = "2.2.20"
coroutines = "1.10.2"
dokka = "2.0.0"

ktlint-gradle = "13.1.0"

turbine = "1.2.1"

[libraries]
kotlin-test = { module = "org.jetbrains.kotlin:kotlin-test", version.ref = "kotlin" }

coroutines-core = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-core", version.ref = "coroutines" }
coroutines-test = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-test", version.ref = "coroutines" }

turbine = { module = "app.cash.turbine:turbine", version.ref = "turbine" }

[plugins]
ktlint = { id = "org.jlleitschuh.gradle.ktlint", version.ref = "ktlint-gradle" }
kotlin-multiplatform = { id = "org.jetbrains.kotlin.multiplatform", version.ref = "kotlin" }
android-library = { id = "com.android.library", version.ref = "android-gradle-plugin" }
dokka = { id = "org.jetbrains.dokka", version.ref = "dokka" }

[bundles]
commonTest = [
    "kotlin-test",
    "coroutines-test",
    "turbine"
]
